const CATEGORIES = [
  { slug: 'smart-tech', label: 'Smart Tech', icon: 'assets/icons/icon-smart-tech.svg' },
  { slug: 'audio', label: 'Audio', icon: 'assets/icons/icon-audio.svg' },
  { slug: 'desk-setup', label: 'Desk Setup', icon: 'assets/icons/icon-desk-setup.svg' },
  { slug: 'accessories', label: 'Accessories', icon: 'assets/icons/icon-accessories.svg' },
  { slug: 'productivity', label: 'Productivity', icon: 'assets/icons/icon-productivity.svg' },
];

const CURRENCY = '₹';

const PRODUCTS = [
  {
    id: 'nx-001',
    name: 'Aurora Smart Desk Lamp',
    category: 'smart-tech',
    price: 2499,
    oldPrice: 3299,
    discount: 24,
    rating: 4.6,
    reviews: 312,
    description: 'A touch-dimmable desk lamp with adaptive warm-to-cool lighting and a built-in wireless charging base.',
    image: 'assets/icons/icon-smart-tech.svg',
    images: ['assets/icons/icon-smart-tech.svg'],
    colors: [
      { name: 'Graphite', hex: '#2B2E33' },
      { name: 'Off-White', hex: '#F4F5F3' },
    ],
    specifications: {
      Material: 'Aluminium + soft-touch silicone',
      Weight: '620 g',
      Compatibility: 'Qi wireless charging, USB-C',
      Warranty: '1 year',
      Dimensions: '38 × 14 × 14 cm',
    },
  },
  {
    id: 'nx-002',
    name: 'Pulse Wireless Earbuds Pro',
    category: 'audio',
    price: 4999,
    oldPrice: 6499,
    discount: 23,
    rating: 4.5,
    reviews: 890,
    description: 'True wireless earbuds with adaptive noise cancellation and 32 hours of total playback with the case.',
    image: 'assets/icons/icon-audio.svg',
    images: ['assets/icons/icon-audio.svg'],
    colors: [
      { name: 'Jet Black', hex: '#0A0B0D' },
      { name: 'Arctic', hex: '#E7E9EC' },
    ],
    specifications: {
      Material: 'Polycarbonate shell',
      Weight: '5.4 g per earbud',
      Compatibility: 'Bluetooth 5.3, USB-C',
      Warranty: '1 year',
      Dimensions: 'Case: 5.6 × 4.8 × 2.6 cm',
    },
  },
  {
    id: 'nx-003',
    name: 'Zenith Mechanical Keyboard',
    category: 'accessories',
    price: 6999,
    oldPrice: 8499,
    discount: 18,
    rating: 4.8,
    reviews: 421,
    description: 'A hot-swappable 75% mechanical keyboard with a machined aluminium frame and per-key backlighting.',
    image: 'assets/icons/icon-accessories.svg',
    images: ['assets/icons/icon-accessories.svg'],
    colors: [
      { name: 'Charcoal', hex: '#2B2E33' },
      { name: 'Ivory', hex: '#F4F5F3' },
    ],
    specifications: {
      Material: 'Aluminium frame, PBT keycaps',
      Weight: '890 g',
      Compatibility: 'USB-C, Bluetooth 5.1',
      Warranty: '2 years',
      Dimensions: '32 × 14 × 3.5 cm',
    },
  },
  {
    id: 'nx-004',
    name: 'Horizon Dual Monitor Arm',
    category: 'desk-setup',
    price: 3799,
    oldPrice: 4999,
    discount: 24,
    rating: 4.4,
    reviews: 156,
    description: 'A gas-spring dual monitor arm that clamps to any desk edge and frees up your entire workspace.',
    image: 'assets/icons/icon-desk-setup.svg',
    images: ['assets/icons/icon-desk-setup.svg'],
    colors: [{ name: 'Matte Black', hex: '#1C1F24' }],
    specifications: {
      Material: 'Cold-rolled steel',
      Weight: '3.2 kg',
      Compatibility: 'VESA 75×75 / 100×100',
      Warranty: '3 years',
      Dimensions: 'Supports up to 27" displays',
    },
  },
  {
    id: 'nx-005',
    name: 'Nimbus Noise-Cancelling Headphones',
    category: 'audio',
    price: 8999,
    oldPrice: 11999,
    discount: 25,
    rating: 4.7,
    reviews: 674,
    description: 'Over-ear headphones with studio-tuned drivers, 40-hour battery life, and industry-leading ANC.',
    image: 'assets/icons/icon-audio.svg',
    images: ['assets/icons/icon-audio.svg'],
    colors: [
      { name: 'Midnight', hex: '#0A0B0D' },
      { name: 'Dune', hex: '#C9BFAF' },
    ],
    specifications: {
      Material: 'Aluminium + memory foam',
      Weight: '265 g',
      Compatibility: 'Bluetooth 5.3, 3.5mm jack',
      Warranty: '1 year',
      Dimensions: 'Foldable, travel case included',
    },
  },
  {
    id: 'nx-006',
    name: 'Vertex Ergonomic Mouse',
    category: 'accessories',
    price: 1899,
    oldPrice: 2399,
    discount: 21,
    rating: 4.3,
    reviews: 203,
    description: 'A vertical ergonomic mouse designed to reduce wrist strain during long work sessions.',
    image: 'assets/icons/icon-accessories.svg',
    images: ['assets/icons/icon-accessories.svg'],
    colors: [{ name: 'Graphite', hex: '#2B2E33' }],
    specifications: {
      Material: 'ABS + rubberised grip',
      Weight: '110 g',
      Compatibility: '2.4GHz dongle + Bluetooth',
      Warranty: '1 year',
      Dimensions: '12.8 × 7.2 × 6.9 cm',
    },
  },
  {
    id: 'nx-007',
    name: 'Flow Smart Power Strip',
    category: 'smart-tech',
    price: 1599,
    oldPrice: 1999,
    discount: 20,
    rating: 4.2,
    reviews: 289,
    description: 'A app-controlled power strip with 4 smart outlets and 3 USB-C ports for a tidy, connected desk.',
    image: 'assets/icons/icon-smart-tech.svg',
    images: ['assets/icons/icon-smart-tech.svg'],
    colors: [{ name: 'Off-White', hex: '#F4F5F3' }],
    specifications: {
      Material: 'Flame-retardant polycarbonate',
      Weight: '340 g',
      Compatibility: 'Wi-Fi 2.4GHz, iOS/Android app',
      Warranty: '1 year',
      Dimensions: '25 × 6 × 3 cm',
    },
  },
  {
    id: 'nx-008',
    name: 'Meridian Desk Organizer',
    category: 'productivity',
    price: 1299,
    oldPrice: 1699,
    discount: 24,
    rating: 4.5,
    reviews: 134,
    description: 'A modular walnut-and-steel organizer for pens, cards, and your phone, built for a calmer desk.',
    image: 'assets/icons/icon-productivity.svg',
    images: ['assets/icons/icon-productivity.svg'],
    colors: [{ name: 'Walnut', hex: '#5C4632' }],
    specifications: {
      Material: 'Walnut wood + powder-coated steel',
      Weight: '780 g',
      Compatibility: 'Universal phone stand slot',
      Warranty: '1 year',
      Dimensions: '22 × 10 × 9 cm',
    },
  },
];

function getCategory(slug) {
  return CATEGORIES.find((c) => c.slug === slug);
}

function formatPrice(amount) {
  return CURRENCY + amount.toLocaleString('en-IN');
}